branch-defaults:
  default:
    environment: weather-outfit-env
  master:
    environment: weather-outfit-env
global:
  application_name: weather-outfit-app
  default_ec2_keyname: vockey
  default_platform: Python 3.9
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
